[project]
name = "simple_drone"
version = "0.1.0"
description = "Add a short description here"
channels = ["robostack-staging", "conda-forge"]
platforms = ["osx-arm64"]

[activation]
scripts = ["install/setup.sh"]

[tasks]
build = "colcon build --symlink-install"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-turtlesim = ">=1.4.2,<1.5"
ros-humble-ament-cmake-auto = ">=1.3.7,<1.4"
pkg-config = ">=0.29.2,<0.30"
compilers = ">=1.7.0,<1.8"
cmake = ">=3.28.3,<3.29"
ninja = ">=1.12.0,<1.13"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
ros-humble-xacro = ">=2.0.8,<2.1"
ros-humble-gazebo-ros = ">=3.7.0,<3.8"
ros-humble-gazebo-plugins = ">=3.7.0,<3.8"
ros-humble-gazebo-msgs = ">=3.7.0,<3.8"
